CREATE TABLE TB_CODEGROUP (
     GROUP_CD VARCHAR(10) NOT NULL
    , GROUP_NM VARCHAR(20) NOT NULL
    , USE_FG VARCHAR(1) NULL
    , CREATE_USER VARCHAR(12) NULL
    , CREATE_DT DATE NULL
    , UPDATE_USER VARCHAR(12) NULL
    , UPDATE_DT DATE NULL
    , GROUP_DESC VARCHAR(100) NULL
    , PRIMARY KEY (GROUP_CD)
);

CREATE TABLE TB_CODE (
     CODE_CD VARCHAR(10) NOT NULL
    , CODE_NM VARCHAR(20) NOT NULL
    , CODE_SEQ INTEGER NULL
    , GROUP_CD VARCHAR(10) NOT NULL
    , USE_FG VARCHAR(1) NULL
    , CREATE_USER VARCHAR(12) NULL
    , CREATE_DT DATE NULL
    , UPDATE_USER VARCHAR(12) NULL
    , UPDATE_DT DATE NULL
    , CODE_GBN VARCHAR(12) NULL
    , CODE_DESC VARCHAR(100) NULL
    , PRIMARY KEY (CODE_CD, GROUP_CD)
);
