CREATE TABLE TB_USER (
      USER_ID VARCHAR(50) NOT NULL
    , USER_NAME VARCHAR(50) NOT NULL
    , EN_NAME VARCHAR(20) NULL
    , COMP_PHONE VARCHAR(20) NULL
    , PHONE VARCHAR(20) NULL
    , CELL_PHONE VARCHAR(20) NULL
    , COMPANY VARCHAR(50) NULL
    , JOB_POSITION VARCHAR(20) NULL
    , ASSIGNMENT VARCHAR(20) NULL
    , OFFICER_YN VARCHAR(20) NULL
    , FAX VARCHAR(20) NULL
    , ZIP_CODE VARCHAR(20) NULL
    , ADDRESS VARCHAR(20) NULL
    , COMP_ZIP_CODE VARCHAR(20) NULL
    , COMP_ADDRESS VARCHAR(20) NULL
    , EMAIL VARCHAR(20) NULL
    , DEPT_ID VARCHAR(20) NULL
    , PASSWORD VARCHAR(20) NOT NULL
    , PRIMARY KEY (USER_ID)
);