CREATE TABLE TB_BOARD (
     POST_ID INTEGER NOT NULL IDENTITY
    , TITLE VARCHAR(150) NOT NULL
    , CONTENTS LONGVARCHAR NULL
    , REG_ID VARCHAR(20) NULL
    , REG_DATE DATE NULL
    , COMMUNITY_ID VARCHAR(16) NULL
    , HIT_COUNT INTEGER NULL
    , PRIMARY KEY (POST_ID)
);